type Question {
    picture_clue_url: String!
    text_clue: String!
    answer: String!
    author: User @relation(name: "question_creator")
    ratings: [Rating] @relation
    usersAnswered: [User] @relation(name: "questions_answered")
}

type User {
    name: String!
    email: String!
    createdQuestions: [Question] @relation(name: "question_creator")
    questionsAnswered: [Question] @relation(name: "questions_answered")
    createdRatings: [Rating] @relation
}

type Rating {
    rater: User! 
    question: Question!
    rating: Int!
}

type Query {
    allQuestions: [Question!]
    allUser: [User!]
    allRatings: [Rating!]
    getUserByName(name: String!): User!
    questions_by_reverse_date: [String!, String!]
}